export default [
  {
    orderId: 'XCA123T',
    items: 10,
    spent: 2000,
    status: 'Delivered',
    address: 'Office No. 14, Tariq Plaza, Karachi',
    createdAt: new Date(),
  },
  {
    orderId: 'XCA124T',
    items: 4,
    spent: 1250,
    status: 'On the way',
    address: '144,Satellite Town, Punjab',
    createdAt: new Date(),
  },
  {
    orderId: 'XCA125T',
    items: 1,
    spent: 610,
    status: 'Cancelled',
    address: 'Rex Center Sadar, Sindh',
    createdAt: new Date(),
  },
  {
    orderId: 'XCA126T',
    items: 2,
    spent: 1630,
    status: 'Delivered',
    address: '11st Floor, Civic Centre New Garden Town, Punjab',
    createdAt: new Date(),
  },
  {
    orderId: 'XCA127T',
    items: 9,
    spent: 4220,
    status: 'On the way',
    address: 'Sector-24, Korangi Industrial Area, Sindh',
    createdAt: new Date(),
  },
];
